SELECT DISTINCT CITY
FROM STATION
WHERE RIGHT(CITY,1)='a' or RIGHT(CITY,1)='e' or RIGHT(CITY,1)='i' or RIGHT(CITY,1)='o' or RIGHT(CITY,1)='u'
;

SELECT DISTINCT CITY
FROM STATION
WHERE RIGHT(CITY,1) IN ('a', 'e', 'i', 'o', 'u')
;

SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE '%a'
    OR CITY LIKE '%e'
    OR CITY LIKE '%i'
    OR CITY LIKE '%o'
    OR CITY LIKE '%u'
;