SELECT DISTINCT CITY
FROM STATION
WHERE LEFT(CITY,1)='a' or LEFT(CITY,1)='e' or LEFT(CITY,1)='i' or LEFT(CITY,1)='o' or LEFT(CITY,1)='u'
;

SELECT DISTINCT CITY
FROM STATION
WHERE LEFT(CITY,1) IN ('a', 'e', 'i', 'o', 'u')
;

SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE 'a%'
    OR CITY LIKE 'e%'
    OR CITY LIKE 'i%'
    OR CITY LIKE 'o%'
    OR CITY LIKE 'u%'
;