SELECT ROUND(A.LAT_N,4)
FROM STATION A
WHERE (SELECT COUNT(*) FROM STATION B WHERE B.LAT_N < A.LAT_N) = (SELECT COUNT(*) FROM STATION C WHERE C.LAT_N > A.LAT_N);

SELECT ROUND(PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY LAT_N), 4)
FROM STATION;

/*
데이터 개수가 홀수인 경우만 가능. '문제 그대로 위쪽 절반과 아래쪽 절반을 정확히 나눈 값'을 정의로 하여금 구하는 과정

*/